### ISSUE TITLE
Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.

### ISSUE THREAD

**Issue by HeyAshh** [hidjou/classsed-react-firebase-functions#13]
Getting this error in terminal when trying to send this code in postman
 ```
{
	"body": "New scream",
	"userHandle": "new"
}
```
![g1](https://user-images.githubusercontent.com/57528612/73253880-67470f00-41ce-11ea-84df-953e28bd855a.png)
Any ideas?

**Comment by HeyAshh** [comment]
This happens 25 minutes into the video btw

**Comment by Bembit** [comment]
Hi. Go to your Firebase dashboard / Settings / Service Account. At the bottom, select the Node JS Firebase Admin SDK, click on Generate Private Key. It should download a JSON for you. Rename it to something more convenient like "db.json", pase it in your /functions folder next to your index.js and insert the below into your index.js. 

Database URL is in your firebase config file.

This should solve it.

`const serviceAccount = require("./db.json");

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: "https://YOURDATABASENAME-NUMBER.firebaseio.com"
});`

**Comment by HeyAshh** [comment]
Been a while, but I think that solved it for me! Thanks!
